AllCops:
  TargetRubyVersion: 2.6
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*.gemfile'
    - 'gemfiles/vendor/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/NumericLiterals:
  Enabled: false
