language: ruby
cache: bundler

sudo: false

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

gemfile:
  - gemfiles/graphql_1_8.gemfile
  - gemfiles/graphql_1_9.gemfile
  - gemfiles/graphql_1_10.gemfile
  - gemfiles/graphql_master.gemfile


notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
